services:
  web_app:
    build: 
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./web_app:/web_app
    environment:
      - DB_HOST=database
      - DB_NAME=db
      - DB_USER=dbuser
      - DB_PASS=pass

    command: > 
      sh -c "python manage.py runserver 0.0.0.0:8000"
    
    depends_on:
      - database

  database:
    image: postgres:16.3-alpine
    environment:
      - POSTGRES_DB=db
      - POSTGRES_USER=dbuser
      - POSTGRES_PASSWORD=pass
